spring:
  application:
    name: Native Config Server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/cmabdullah23/ConfigRepo.git
          default-label: main
        health:
          enabled: true
    refresh:
      enabled: false            # disable refresh scope for AOT

server:
  port: 8098

management:
  endpoints:
    web:
      exposure:
        include: '*'
